services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=your-gemini-api-key-here
    volumes:
      - ./app:/app/app         # Flaskコードはここ
      - ./db:/app/db           # SQLiteは /app/db/tasks.db に保存

